Repository connect-foundation/2019-03, pull requests merged in 2019-11, with the labels that each got.

#82 [Feat] more modal에 관련된 기능 추가
  web/package-lock.json
  web/package.json
  web/src/components/PostTop/MoreModal/ModalBackground.js
  web/src/components/PostTop/MoreModal/index.js
  web/src/components/PostTop/index.js
Labels: feature

#83 [Refactor] PostContent 의 본문 컴포넌트 수정
  web/src/components/Comment/index.js
  web/src/components/PostContent/index.js
  web/src/components/PostText/Wrapper.js
  web/src/components/PostText/index.js
Labels: refactor

#84 [Feat] sequelize를 이용한 Database setting
  api-server/.env
  api-server/.sequelizerc
  api-server/api/models/.gitkeep
  api-server/api/models/hashtag.js
  api-server/api/models/post.js
  api-server/api/models/reply.js
  api-server/api/models/user.js
  api-server/api/models/userfollow.js
  api-server/config/.gitkeep
  api-server/config/sequelize-config.js
  api-server/db/index.js
  api-server/db/migrations/20191117094148-create-user.js
  api-server/db/migrations/20191117104241-create-post.js
  api-server/db/migrations/20191117124029-associate-user-post.js
  api-server/db/migrations/20191117125445-associate-user-post.js
  api-server/db/migrations/20191117131058-associate-user-post.js
  api-server/db/migrations/20191117131642-create-hash-tag.js
  api-server/db/migrations/20191117132239-associate-user-hashtag.js
  api-server/db/migrations/20191117132947-associate-post-hashtag.js
  api-server/db/migrations/20191117140021-create-reply.js
  api-server/db/migrations/20191117143438-associate-user-reply.js
  api-server/db/migrations/20191118062418-create-user-follow.js
  api-server/package-lock.json
  api-server/package.json
Labels: feature

#100 [Refact] PostTop관련 컴포넌트 구조 변경
  web/src/components/PostTop/MoreIcon.js
  web/src/components/PostTop/MoreModal/ModalBackground.js
  web/src/components/PostTop/MoreModal/ModalContent.js
  web/src/components/PostTop/MoreModal/ModalWrapper.js
  web/src/components/PostTop/MoreModal/index.js
  web/src/components/PostTop/MoreModal/styles.js
  web/src/components/PostTop/PostTopWrapper.js
  web/src/components/PostTop/index.js
  web/src/components/PostTop/styles.js
  web/src/components/StyledLink.js
Labels: refactor

#99 [Refactor] LikeIcon을 응용해 아이콘에 대한 공통 모듈인 Icon 구현
  web/src/components/Icon/IconImage.js
  web/src/components/Icon/index.js
  web/src/components/LikeIcon/index.js
Labels: refactor

#98 [Feat] post detail page
  web/src/components/Comment/index.js
  web/src/components/CommentInput/Wrapper.js
  web/src/components/CommentList/Wrapper.js
  web/src/components/Icon/IconImage.js
  web/src/components/PostContent/Wrapper.js
  web/src/components/PostTop/PostTopWrapper.js
  web/src/containers/App/index.js
  web/src/containers/PostDetailPage/PostDetailPageWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/CommentListWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/MoreCommentButton.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/styles.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/PostContentWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostText/BottomButtonGroup.js
  web/src/containers/PostDetailPage/PostSideBox/PostText/FlexBlock.js
  web/src/containers/PostDetailPage/PostSideBox/PostText/PostTextWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/PostText/ProfileWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/PostText/StyledTime.js
  web/src/containers/PostDetailPage/PostSideBox/PostText/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostText/styles.js
  web/src/containers/PostDetailPage/PostSideBox/SideBoxWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/IconBox.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/UtilityBlockWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/styles.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/containers/PostDetailPage/ViewPort.js
  web/src/containers/PostDetailPage/index.js
  web/src/containers/PostDetailPage/styles.js
Labels: feature

#102 검색창 UI 구현하면서 아이콘 props 수정
  web/src/components/Icon/index.js
  web/src/containers/Navigation/Serach/Input.js
  web/src/containers/Navigation/Serach/SearchWrapper.js
  web/src/containers/Navigation/Serach/index.js
  web/src/containers/Navigation/index.js
Labels: urgent

#103 [Fix] 프로필 아이콘 이미지 동적 할당
  web/src/components/ProfileIcon/index.js
Labels: fix

#104 [Refact] 프로필 아이콘 구조 변경
  web/src/components/PostTop/index.js
  web/src/components/ProfileIcon/ProfileIconWrapper.js
  web/src/components/ProfileIcon/Wrapper.js
  web/src/components/ProfileIcon/index.js
  web/src/containers/PostDetailPage/index.js
  web/src/images/queen.jpg
Labels: refactor

#108 [Refact] Modal 컴포넌트 구현
  web/src/components/Modal/ModalBackground.js
  web/src/components/Modal/ModalWrapper.js
  web/src/components/Modal/index.js
  web/src/components/Modal/styles.js
  web/src/components/PostTop/MoreModal/index.js
  web/src/components/PostTop/MoreModal/styles.js
Labels: front, refactor

#110 [Feat] 네비게이션 전체 UI 구현
  web/src/components/StyledLink.js
  web/src/containers/App/index.js
  web/src/containers/Navigation/NavBackground.js
  web/src/containers/Navigation/NavItemGroup.js
  web/src/containers/Navigation/Search/Input.js
  web/src/containers/Navigation/Search/SearchWrapper.js
  web/src/containers/Navigation/Search/index.js
  web/src/containers/Navigation/Search/styles.js
  web/src/containers/Navigation/index.js
  web/src/containers/Navigation/styles.js
  web/src/containers/NewPostPage/index.js
  web/src/index.js
Labels: front

#111 [Fix] 네이게이션 마진 수정
  web/src/containers/App/index.js
  web/src/containers/Navigation/NavBackground.js
  web/src/containers/Navigation/Search/SearchWrapper.js
Labels: urgent

#112 [Feat] 팔로우 버튼 구현
  web/src/components/FollowButton/StyledFollowButton.js
  web/src/components/FollowButton/index.js
Labels: feature, front

#114 [Feat] 상세 페이지 UI 구현
  web/src/components/Comment/Wrapper.js
  web/src/components/Comment/index.js
  web/src/components/CommentInput/Wrapper.js
  web/src/containers/PostDetailPage/PostDetailPageWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/index.js
  web/src/containers/PostDetailPage/PostSideBox/SideBoxWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/IconBox.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/IconList.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/IconWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/LikerCount.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/TimePassed.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/UtilityBlockWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/styles.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/containers/PostDetailPage/ViewPort.js
  web/src/containers/PostDetailPage/index.js
Labels: feature, front

#115 [Refact] Comment 컴포넌트 구조 정리
  web/src/components/Comment/CommentWrapper.js
  web/src/components/Comment/Content/ContentWrapper.js
  web/src/components/Comment/Content/GrayButton.js
  web/src/components/Comment/Content/StyledTime.js
  web/src/components/Comment/Content/index.js
  web/src/components/Comment/Content/styles.js
  web/src/components/Comment/LikeIconWrapper.js
  web/src/components/Comment/ProfileWrapper.js
  web/src/components/Comment/Wrapper.js
  web/src/components/Comment/index.js
  web/src/components/Comment/styles.js
Labels: refactor

#113 [Feat] 좋아요 갯수를 표시하는 LikeInfo 컴포넌트 구현
  web/src/components/Icon/IconImage.js
  web/src/components/LikeInfo/LikeCount.js
  web/src/components/LikeInfo/LikeInfoWrapper.js
  web/src/components/LikeInfo/LikerLink.js
  web/src/components/LikeInfo/LikerListModal/Header/ButtonWrapper.js
  web/src/components/LikeInfo/LikerListModal/Header/Cancel.js
  web/src/components/LikeInfo/LikerListModal/Header/HeaderWrapper.js
  web/src/components/LikeInfo/LikerListModal/Header/Title.js
  web/src/components/LikeInfo/LikerListModal/Header/index.js
  web/src/components/LikeInfo/LikerListModal/Header/styles.js
  web/src/components/LikeInfo/LikerListModal/Liker/FollowButton.js
  web/src/components/LikeInfo/LikerListModal/Liker/LikerInfo.js
  web/src/components/LikeInfo/LikerListModal/Liker/LikerInfoWrapper.js
  web/src/components/LikeInfo/LikerListModal/Liker/LikerWrapper.js
  web/src/components/LikeInfo/LikerListModal/Liker/index.js
  web/src/components/LikeInfo/LikerListModal/Liker/styles.js
  web/src/components/LikeInfo/LikerListModal/LikerList.js
  web/src/components/LikeInfo/LikerListModal/index.js
  web/src/components/LikeInfo/LikerListModal/styles.js
  web/src/components/LikeInfo/Profile.js
  web/src/components/LikeInfo/index.js
  web/src/components/LikeInfo/styles.js
Labels: feature, front

#129 [Feat] 검색 기능 구현
  api-server/api/graphql/index.js
  api-server/api/graphql/queries/.gitkeep
  api-server/api/graphql/queries/SearchHashtagQuery.js
  api-server/api/graphql/queries/SearchUserQuery.js
  api-server/api/graphql/types/.gitkeep
  api-server/api/graphql/types/SearchHashtagType.js
  api-server/api/graphql/types/SearchUserType.js
  web/src/components/PostTop/PostTopWrapper.js
  web/src/components/ProfileIcon/ProfileIconWrapper.js
  web/src/components/StyledLink.js
  web/src/components/ToolTip/ToolTipArrow.js
  web/src/components/ToolTip/ToolTipBody.js
  web/src/components/ToolTip/ToolTipWrapper.js
  web/src/components/ToolTip/index.js
  web/src/components/ToolTip/styles.js
  web/src/containers/Navigation/NavBackground.js
  web/src/containers/Navigation/Search/Input.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResult/ResultInfo.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResult/SearchResultWrapper.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResult/index.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResult/styles.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResultList.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchToolTipWrapper.js
  web/src/containers/Navigation/Search/SearchToolTip/index.js
  web/src/containers/Navigation/Search/SearchToolTip/styles.js
  web/src/containers/Navigation/Search/SearchWrapper.js
  web/src/containers/Navigation/Search/index.js
  web/src/containers/Navigation/index.js
  web/src/images/hashtag.png
Labels: feature

#128 [Feat] 게시물 레이아웃 구현
  web/src/components/CommentInput/index.js
  web/src/containers/HomePage/Post/PostBottom/AllCommentShowButton.js
  web/src/containers/HomePage/Post/PostBottom/Comment/CommentContent.js
  web/src/containers/HomePage/Post/PostBottom/Comment/CommentMoreButton.js
  web/src/containers/HomePage/Post/PostBottom/Comment/CommentWrapper.js
  web/src/containers/HomePage/Post/PostBottom/Comment/Commenter.js
  web/src/containers/HomePage/Post/PostBottom/Comment/index.js
  web/src/containers/HomePage/Post/PostBottom/Comment/styles.js
  web/src/containers/HomePage/Post/PostBottom/CommentIcon.js
  web/src/containers/HomePage/Post/PostBottom/CommentInputWrapper.js
  web/src/containers/HomePage/Post/PostBottom/CommentWrapper.js
  web/src/containers/HomePage/Post/PostBottom/IconGroup.js
  web/src/containers/HomePage/Post/PostBottom/IconWrapper.js
  web/src/containers/HomePage/Post/PostBottom/PostBottomWrapper.js
  web/src/containers/HomePage/Post/PostBottom/ShareIcon.js
  web/src/containers/HomePage/Post/PostBottom/UpdatedTime.js
  web/src/containers/HomePage/Post/PostBottom/index.js
  web/src/containers/HomePage/Post/PostBottom/styles.js
  web/src/containers/HomePage/Post/PostImage.js
  web/src/containers/HomePage/Post/PostWrapper.js
  web/src/containers/HomePage/Post/index.js
  web/src/containers/HomePage/Post/styles.js
  web/src/containers/HomePage/PostList/PostListWrapper.js
  web/src/containers/HomePage/PostList/index.js
  web/src/containers/HomePage/index.js
Labels: feature, front

#137 [Refact] 파일 정리
  api-server/bin/server.js
  api-server/db/migrations/20191117094148-create-user.js
  api-server/db/migrations/20191117104241-create-post.js
  api-server/db/migrations/20191117124029-associate-user-post.js
  api-server/db/migrations/20191117125445-associate-user-post.js
  api-server/db/migrations/20191117131058-associate-user-post.js
  api-server/db/migrations/20191117131642-create-hash-tag.js
  api-server/db/migrations/20191117132239-associate-user-hashtag.js
  api-server/db/migrations/20191117132947-associate-post-hashtag.js
  api-server/db/migrations/20191117140021-create-reply.js
  api-server/db/migrations/20191117143438-associate-user-reply.js
  api-server/db/migrations/20191118062418-create-user-follow.js
  api-server/db/seeders/20191120020931-user.js
  api-server/db/seeders/20191121020931-post.js
  api-server/db/seeders/20191122020931-replies.js
  api-server/db/seeders/20191123020931-hashTag.js
Labels: refactor

#138 [Refact] Comment 컴포넌트 위치 이동
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/CommentWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/Content/ContentWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/Content/GrayButton.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/Content/UpdatedTime.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/Content/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/Content/styles.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/LikeIconWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/ProfileWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/styles.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/index.js
Labels: refactor

#142 [Fix] sequelize post model 수정
  api-server/api/models/post.js
Labels: unconfirmed-bug, urgent

#145 [Feat] FollowCheckingModal 구현
  web/src/components/FollowButton/index.js
  web/src/components/FollowCheckingModal/ModalHeaderText.js
  web/src/components/FollowCheckingModal/index.js
  web/src/components/FollowCheckingModal/styles.js
Labels: front

#143 [Refact] 검색에 대한 버그 수정
  web/src/components/ToolTip/ToolTipBody.js
  web/src/containers/Navigation/Search/index.js
Labels: confirmed-bug

#163 [Feat] 상세 페이지 API
  api-server/.env
  api-server/.gitignore
  api-server/api/graphql/index.js
  api-server/api/graphql/queries/CommentQuery.js
  api-server/api/graphql/queries/PostDetailQuery.js
  api-server/api/graphql/types/CommentType.js
  api-server/api/graphql/types/PostDetailType.js
  api-server/api/graphql/types/WriterType.js
  api-server/api/models/comment.js
  api-server/api/models/post.js
  api-server/api/models/postlike.js
  api-server/db/migrations/20191117125445-associate-user-post.js
  api-server/db/migrations/20191117140021-create-comment.js
  api-server/db/migrations/20191117143438-associate-user-comment.js
  api-server/db/seeders/20191122020931-comments.js
  api-server/db/seeders/20191124020931-postlikes.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/Content/ContentWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/Content/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/Comment/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentList/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/PostText/Content/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/PostText/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/index.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/containers/PostDetailPage/ViewPort.js
  web/src/containers/PostDetailPage/context.js
  web/src/containers/PostDetailPage/index.js
  web/src/containers/PostDetailPage/reducer.js
  web/src/images/image.jpg
  web/src/useFetch.js
Labels: back, feature, front

#164 [Fix] URL에 따라 상세 페이지로 라우팅
  web/src/containers/App/index.js
  web/src/containers/PostDetailPage/index.js
Labels: fix, front

#165 [Feat] 메인페이지 이벤트 핸들러 구현
  web/src/components/CommentInput/Wrapper.js
  web/src/components/CommentInput/index.js
  web/src/components/LikeIcon/Context/LikeContext.js
  web/src/components/LikeIcon/index.js
  web/src/components/LikeInfo/Context/LikerListContext.js
  web/src/components/LikeInfo/Profile.js
  web/src/components/LikeInfo/index.js
  web/src/containers/HomePage/Post/AllCommentShowText.js
  web/src/containers/HomePage/Post/Comment/CommentContent.js
  web/src/containers/HomePage/Post/Comment/CommentMoreButton.js
  web/src/containers/HomePage/Post/Comment/CommentWrapper.js
  web/src/containers/HomePage/Post/Comment/Commenter.js
  web/src/containers/HomePage/Post/Comment/index.js
  web/src/containers/HomePage/Post/Comment/styles.js
  web/src/containers/HomePage/Post/Comment/useComment.js
  web/src/containers/HomePage/Post/CommentIcon.js
  web/src/containers/HomePage/Post/CommentInputWrapper.js
  web/src/containers/HomePage/Post/IconGroup.js
  web/src/containers/HomePage/Post/IconWrapper.js
  web/src/containers/HomePage/Post/PostBottom/AllCommentShowButton.js
  web/src/containers/HomePage/Post/PostBottom/Comment/CommentContent.js
  web/src/containers/HomePage/Post/PostBottom/Comment/CommentWrapper.js
  web/src/containers/HomePage/Post/PostBottom/Comment/index.js
  web/src/containers/HomePage/Post/PostBottom/index.js
  web/src/containers/HomePage/Post/PostBottom/styles.js
  web/src/containers/HomePage/Post/PostBottomWrapper.js
  web/src/containers/HomePage/Post/PostImage.js
  web/src/containers/HomePage/Post/ShareIcon.js
  web/src/containers/HomePage/Post/UpdatedTime.js
  web/src/containers/HomePage/Post/index.js
  web/src/containers/HomePage/Post/styles.js
Labels: feature, front

#175 [Refact] useFetch
  api-server/api/graphql/types/CommentType.js
  web/src/components/CommentInput/index.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/containers/PostDetailPage/PostSideBox/reducer.js
  web/src/containers/PostDetailPage/index.js
  web/src/hooks/index.js
  web/src/hooks/useFetch.js
Labels: refactor

#176 [Fix] test data 수정
  web/src/containers/Navigation/index.js
Labels: urgent

#177 [Feat] 댓글 더보기 기능
  api-server/db/seeders/20191122020931-comments.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/CommentWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/Content/ContentWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/Content/GrayButton.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/Content/UpdatedTime.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/Content/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/Content/styles.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/LikeIconWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/ProfileWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/styles.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/CommentListWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/MoreCommentButton.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/styles.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/index.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/containers/PostDetailPage/PostSideBox/reducer.js
Labels: urgent

#184 [Fix] 데모용 시더파일 수정
  api-server/db/seeders/20191120020931-user.js
  api-server/db/seeders/20191121020931-post.js
  api-server/db/seeders/20191124110517-userFollows.js
  api-server/db/seeders/20191125063643-log.js
Labels: urgent

#185 [Fix] 상세 페이지 게시물 imgaeURL 변경
  api-server/db/seeders/20191122020931-comments.js
  web/src/containers/PostDetailPage/index.js
Labels: urgent

#188 [Fix] PostCardList margin-left 버그 수정
  web/src/components/PostCardList/PostCardLine/PostCard/MarginalPostCard.js
Labels: confirmed-bug, fix
