Repository connect-foundation/2019-03, pull requests merged in 2019-12, with the labels that each got.

#196 [Fix] 새게시물 관련 오류 수정
  api-server/app.js
  api-server/upload.js
  web/src/containers/App/index.js
  web/src/containers/Navigation/index.js
Labels: confirmed-bug

#195 [Feat] 메인페이지 무한 스크롤링 기능 구현
  api-server/api/graphql/queries/FollowingPostListQuery.js
  api-server/api/services/PostService.js
  web/src/containers/HomePage/Post/index.js
  web/src/containers/HomePage/index.js
  web/src/containers/HomePage/queries/followingPostList.js
  web/src/containers/HomePage/reducer.js
  web/src/utils/index.js
Labels: back, feature, front

#202 [Refact] 검색 기능 리팩토링
  api-server/api/graphql/queries/SearchHashtagQuery.js
  api-server/api/graphql/queries/SearchUserQuery.js
  web/src/components/ToolTip/ToolTipArrow.js
  web/src/components/ToolTip/ToolTipBackground.js
  web/src/components/ToolTip/ToolTipBody.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmNoResult.js
  web/src/containers/Navigation/Search/Input.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchNoResult.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResult/ResultInfo.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResult/SearchResultWrapper.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResult/index.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchToolTipWrapper.js
  web/src/containers/Navigation/Search/SearchToolTip/index.js
  web/src/containers/Navigation/Search/SearchToolTip/styles.js
  web/src/containers/Navigation/Search/index.js
  web/src/query/navigationQuery.js
Labels: refactor

#204 [Feat] oauth-server 디렉토리 구조 생성
  oauth-server/.gitignore
  oauth-server/app.js
  oauth-server/bin/www
  oauth-server/oauth/src/error-types/.gitkeep
  oauth-server/oauth/src/grant-types/.gitkeep
  oauth-server/oauth/src/handlers/.gitkeep
  oauth-server/oauth/src/response-types/.gitkeep
  oauth-server/oauth/src/utils/.gitkeep
  oauth-server/oauth/src/validator/.gitkeep
  oauth-server/oauth/test/.gitkeep
  oauth-server/package-lock.json
  oauth-server/package.json
  oauth-server/public/.gitkeep
  oauth-server/routes/index.js
  oauth-server/views/error.jade
  oauth-server/views/index.jade
  oauth-server/views/layout.jade
Labels: feature

#205 [Feat] authorization server의 sequelize 설정
  oauth-server/.gitignore
  oauth-server/.sequelizerc
  oauth-server/config/sequelize-config.js
  oauth-server/db/index.js
  oauth-server/db/migrations/20191203063359-create-client.js
  oauth-server/db/seeders/.gitkeep
  oauth-server/models/client.js
  oauth-server/package-lock.json
  oauth-server/package.json
Labels: feature, oauth

#201 [Fix] docker 및 nginx 설정 변경
  api-server/app.js
  api-server/db/.gitkeep
  compose-dev.yml
  compose-prod.yml
  web/config/nginx/conf.d/default.conf
Labels: fix

#208 [Feat] Validator 클래스 구현
  oauth-server/oauth/src/validator/.gitkeep
  oauth-server/oauth/src/validator/index.js
  oauth-server/oauth/test/.gitkeep
  oauth-server/oauth/test/validator/validator.test.js
  oauth-server/package-lock.json
  oauth-server/package.json
Labels: feature, oauth

#198 [Feat] 공유 아이콘 & 모달 구현
  web/src/components/PostTop/MoreModal/index.js
  web/src/components/ShareIcon/index.js
  web/src/components/ShareModal/index.js
  web/src/containers/HomePage/Post/PostMiiddle/ShareIcon.js
  web/src/containers/HomePage/Post/PostMiiddle/index.js
  web/src/containers/HomePage/Post/PostMiiddle/styles.js
Labels: feature, front

#209 [Feat] OAuth 2.0의 Error Response에 대한 Error 클래스 구현
  oauth-server/oauth/src/error-types/.gitkeep
  oauth-server/oauth/src/error-types/access-denied-error.js
  oauth-server/oauth/src/error-types/index.js
  oauth-server/oauth/src/error-types/invalid-client-error.js
  oauth-server/oauth/src/error-types/invalid-grant-error.js
  oauth-server/oauth/src/error-types/invalid-request-error.js
  oauth-server/oauth/src/error-types/invalid-scope-error.js
  oauth-server/oauth/src/error-types/server-error.js
  oauth-server/oauth/src/error-types/temporarily-unavailable-error.js
  oauth-server/oauth/src/error-types/unauthorized-client-error.js
  oauth-server/oauth/src/error-types/unsupported-grant-type-error.js
  oauth-server/oauth/src/error-types/unsupported-response-type-error.js
  oauth-server/oauth/test/error-types/error-types.test.js
  oauth-server/package.json
Labels: feature, oauth

#215 [Refact] 메인 페이지 리팩토링
  web/package-lock.json
  web/package.json
  web/src/containers/HomePage/Post/CommentInput/CommentInputWrapper.js
  web/src/containers/HomePage/Post/CommentInput/StyledButton.js
  web/src/containers/HomePage/Post/CommentInput/StyledForm.js
  web/src/containers/HomePage/Post/CommentInput/StyledInput.js
  web/src/containers/HomePage/Post/CommentInput/index.js
  web/src/containers/HomePage/Post/CommentInput/reducer.js
  web/src/containers/HomePage/Post/CommentInput/styles.js
  web/src/containers/HomePage/Post/PostBottom/CommentInputWrapper.js
  web/src/containers/HomePage/Post/PostBottom/index.js
  web/src/containers/HomePage/Post/PostBottom/styles.js
  web/src/containers/HomePage/Post/PostMiddle/CommentIcon.js
  web/src/containers/HomePage/Post/PostMiddle/IconGroup.js
  web/src/containers/HomePage/Post/PostMiddle/IconWrapper.js
  web/src/containers/HomePage/Post/PostMiddle/PostImage.js
  web/src/containers/HomePage/Post/PostMiddle/PostMiddleWrapper.js
  web/src/containers/HomePage/Post/PostMiddle/index.js
  web/src/containers/HomePage/Post/PostMiddle/styles.js
  web/src/containers/HomePage/Post/PostText/Comment/index.js
  web/src/containers/HomePage/Post/index.js
  web/src/containers/HomePage/index.js
  web/src/containers/HomePage/queries/createComment.js
  web/src/containers/HomePage/queries/followingPostList.js
  web/src/containers/HomePage/queries/index.js
  web/src/containers/HomePage/reducer.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/CommentInputWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/StyledButton.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/StyledForm.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/StyledInput.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/reducer.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/styles.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/containers/PostDetailPage/queries/index.js
Labels: refactor

#213 [Feat] client register 구현
  oauth-server/db/index.js
  oauth-server/db/migrations/20191203063359-create-client.js
  oauth-server/models/client.js
  oauth-server/oauth/src/validator/index.js
  oauth-server/oauth/test/validator/registration.test.js
  oauth-server/package-lock.json
  oauth-server/package.json
  oauth-server/routes/index.js
  oauth-server/services/registration.js
Labels: feature, oauth

#220 [Refact] nav_alarm 리팩토링
  api-server/api/graphql/queries/LogQuery.js
  api-server/api/graphql/types/LogType.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResultList.js
  web/src/containers/Navigation/Alarm/index.js
  web/src/containers/Navigation/Search/index.js
  web/src/containers/Navigation/query/index.js
  web/src/useFetch.js
Labels: refactor

#221 [Feat] Access Token & Refresh Token 생성기 구현
  oauth-server/oauth/src/utils/.gitkeep
  oauth-server/oauth/src/utils/index.js
  oauth-server/oauth/test/utils/utils.test.js
  oauth-server/oauth/test/validator/validator.test.js
  oauth-server/package-lock.json
  oauth-server/package.json
  oauth-server/services/registration.js
  oauth-server/test/services/registration.test.js
Labels: feature, oauth

#223 [Refact] newpost page
  web/src/containers/NewPostPage/cropImage.js
  web/src/containers/NewPostPage/index.js
Labels: refactor

#224 [Feat] newpost hashtag & user tag
  api-server/api/models/HashTagOfPost.js
  api-server/api/models/UserTag.js
  api-server/api/services/PostService.js
  api-server/app.js
  api-server/db/migrations/20191117131058-associate-user-post.js
Labels: feature

#227 [Fix] 새게시물 페이지 오류 수정
  web/src/containers/NewPostPage/NewPostWrapper.js
  web/src/containers/NewPostPage/index.js
Labels: confirmed-bug

#228 [Fix] 사용자 페이지간 이동 시 PostCardList 최신화
  web/src/containers/UserPage/index.js
Labels: fix

#237 [Fix] html, manifest.json 파일 수정
  web/public/index.html
  web/public/manifest.json
Labels: urgent

#257 [Fix] 스크롤 이슈 해결
  web/src/containers/HomePage/index.js
Labels: fix

#258 [Feat] 회원가입 및 로그인 기능 구현
  api-server/api/middlewares/Authenticator.js
  api-server/api/models/User.js
  api-server/api/routes/AccountRoute.js
  api-server/api/services/UserService.js
  api-server/app.js
  api-server/db/migrations/20191117094148-create-user.js
  api-server/package-lock.json
  api-server/package.json
  api-server/test/.gitkeep
  api-server/test/api/AccountRoute.test.js
  api-server/test/services/PostService.test.js
  api-server/test/services/UserService.test.js
  api-server/utils/bcrypt.js
Labels: back, feature

#262 [Fix] 메인 페이지 버그 수정
  web/src/containers/HomePage/index.js
Labels: fix

#263 [Fix] 검색기능 버그 수정
  api-server/api/graphql/queries/SearchQuery.js
Labels: confirmed-bug

#268 [Feat] UserPage의 UserInfo 구현
  api-server/api/graphql/queries/UserPageQuery.js
  api-server/api/graphql/types/UserInfoType.js
  api-server/api/graphql/types/UserPageType.js
  api-server/api/services/UserPageService.js
  web/src/containers/App/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
  web/src/containers/UserPage/UserPageInfo/index.js
  web/src/containers/UserPage/index.js
Labels: back, feature, front, refactor

#270 [Feat] FollowButton 팔로우 요청, 팔로우 취소 요청 구현
  api-server/api/graphql/index.js
  api-server/api/graphql/mutations/RequestFollowing.js
  api-server/api/graphql/mutations/RequestFollowingCancellation.js
  api-server/api/graphql/mutations/index.js
  api-server/api/graphql/types/UserFollower.js
  api-server/api/graphql/types/UserInfoType.js
  api-server/api/graphql/types/index.js
  api-server/app.js
  web/src/components/FollowButton/StyledFollowButton.js
  web/src/components/FollowButton/index.js
  web/src/components/FollowCheckingModal/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/StyledFollowButton.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
  web/src/containers/UserPage/UserPageInfo/index.js
  web/src/containers/UserPage/index.js
Labels: back, feature

#274 [Fix] 좋아요 문구 버그 수정
  web/src/components/LikeIcon/index.js
  web/src/components/LikeInfo/Context/LikerInfoContext.js
  web/src/containers/HomePage/Post/PostMiddle/index.js
Labels: confirmed-bug, fix, front

#275 [fix] UD 기능 수정
  web/src/components/PostTop/MoreModal/index.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
Labels: fix

#281 [Feat] client registration page
  web/package-lock.json
  web/package.json
  web/src/containers/App/index.js
  web/src/containers/DeveloperPage/Registration/Button.js
  web/src/containers/DeveloperPage/Registration/Input.js
  web/src/containers/DeveloperPage/Registration/P.js
  web/src/containers/DeveloperPage/Registration/RegistrationWrapper.js
  web/src/containers/DeveloperPage/Registration/Select.js
  web/src/containers/DeveloperPage/Registration/Span.js
  web/src/containers/DeveloperPage/Registration/Title.js
  web/src/containers/DeveloperPage/Registration/index.js
  web/src/containers/DeveloperPage/Registration/styles.js
  web/src/containers/DeveloperPage/index.js
Labels: feature, front

#276 [Fix] 게시물 이미지 더블클릭 이벤트 버그 수정
  web/src/containers/HomePage/Post/PostMiddle/PostImage.js
  web/src/containers/HomePage/Post/PostMiddle/index.js
Labels: confirmed-bug, fix

#285 [Fix] 새게시물 버그 수정
  api-server/app.js
  api-server/db/seeders/20191124035711-commentLikes.js
  web/config/nginx/conf.d/default.conf
  web/src/containers/NewPostPage/index.js
Labels: confirmed-bug

#286 [Feat] 에러 페이지 구현
  web/src/containers/ErrorPage/ErrorImage.js
  web/src/containers/ErrorPage/ErrorWrapper.js
  web/src/containers/ErrorPage/index.js
  web/src/containers/ErrorPage/styles.js
  web/src/containers/PostDetailPage/index.js
Labels: feature, front

#287 [Feat] HashTagPage구현
  api-server/api/graphql/index.js
  api-server/api/graphql/queries/hashTagPageQuery.js
  api-server/api/graphql/queries/index.js
  api-server/api/graphql/types/HashTagPageType.js
  api-server/api/graphql/types/index.js
  web/src/containers/App/index.js
  web/src/containers/HashTagPage/HashTagInfoDetailWrapper.js
  web/src/containers/HashTagPage/HashTagInfoWrapper.js
  web/src/containers/HashTagPage/HashTagPageWrapper.js
  web/src/containers/HashTagPage/PostCardListWrapper.js
  web/src/containers/HashTagPage/index.js
  web/src/containers/HashTagPage/styles.js
Labels: back, feature, front

#288 [Refact] 전체 페이지 배경색 변경
  web/src/components/PostTop/PostTopWrapper.js
  web/src/containers/HomePage/Post/PostMiddle/PostImage.js
  web/src/containers/HomePage/Post/PostWrapper.js
  web/src/containers/PostDetailPage/PostDetailPageWrapper.js
  web/src/index.js
Labels: front

#305 [Fix] 오타 수정
  api-server/api/graphql/mutations/UserMutation.js
  api-server/api/graphql/types/index.js
Labels: fix

#303 [Fix] 검색 툴팁 UI 변경, 링크 추가
  web/src/components/ToolTip/ToolTipArrow.js
  web/src/components/ToolTip/ToolTipBody.js
  web/src/components/ToolTip/ToolTipWrapper.js
  web/src/containers/Navigation/Search/Input.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResult/index.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchResultList.js
  web/src/containers/Navigation/Search/SearchToolTip/SearchToolTipWrapper.js
  web/src/containers/Navigation/Search/SearchToolTip/index.js
  web/src/containers/Navigation/Search/index.js
Labels: fix, front

#289 [Feat] 설정 페이지 UI 구현
  api-server/api/graphql/index.js
  api-server/api/graphql/mutations/UserMutation.js
  api-server/api/graphql/mutations/index.js
  api-server/db/migrations/20191117094148-create-user.js
  web/.eslintrc.js
  web/src/components/Button/index.js
  web/src/components/Form/index.js
  web/src/components/Input/index.js
  web/src/components/InputRow/InputRowWrapper.js
  web/src/components/InputRow/StyledAside.js
  web/src/components/InputRow/StyledLabel.js
  web/src/components/InputRow/index.js
  web/src/components/InputRow/styles.js
  web/src/containers/App/index.js
  web/src/containers/ChangePasswordPage/index.js
  web/src/containers/DeveloperPage/Registration/Button.js
  web/src/containers/DeveloperPage/Registration/RegistrationWrapper.js
  web/src/containers/DeveloperPage/Registration/styles.js
  web/src/containers/DeveloperPage/index.js
  web/src/containers/EditProfilePage/index.js
  web/src/containers/EditProfilePage/queries/index.js
  web/src/containers/RegisterAppPage/P.js
  web/src/containers/RegisterAppPage/Select.js
  web/src/containers/RegisterAppPage/Span.js
  web/src/containers/RegisterAppPage/Title.js
  web/src/containers/RegisterAppPage/index.js
  web/src/containers/RegisterAppPage/styles.js
  web/src/containers/SettingPage/List/Item/ItemWrapper.js
  web/src/containers/SettingPage/List/Item/index.js
  web/src/containers/SettingPage/List/ListWrapper.js
  web/src/containers/SettingPage/List/index.js
  web/src/containers/SettingPage/SettingPageWrapper.js
  web/src/containers/SettingPage/index.js
  web/src/containers/SettingPage/styles.js
Labels: feature, front, needs-feedback

#314 ErrorPage를 Error컴포넌트로 변경
  web/src/components/Error/ErrorImage.js
  web/src/components/Error/ErrorWrapper.js
  web/src/components/Error/index.js
  web/src/components/Error/styles.js
  web/src/containers/PostDetailPage/index.js
Labels: front, refactor

#311 해쉬태그 페이지 리팩토링 및 AnnouncementMessage 구현
  api-server/api/graphql/queries/hashTagPageQuery.js
  api-server/api/services/HashTagPageService.js
  web/src/components/AnnouncementMessage/AnnouncementMessageWrapper.js
  web/src/components/AnnouncementMessage/index.js
  web/src/containers/HashTagPage/index.js
Labels: back, feature, front, refactor

#313 [Fix] 스피너 위치를 상위 컴포넌트의 가운데에 오도록 수정
  web/src/components/Loading/Backdrop.js
  web/src/components/Loading/SpinnerWrapper.js
  web/src/components/Loading/index.js
  web/src/components/Loading/styles.js
  web/src/containers/HomePage/Post/CommentInput/CommentInputWrapper.js
  web/src/containers/HomePage/Post/CommentInput/StyledButton.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/CommentInputWrapper.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/StyledButton.js
Labels: confirmed-bug

#310 [Fix] 알람 툴팁 관련 버그 수정
  api-server/api/graphql/queries/LogQuery.js
  api-server/api/graphql/types/AlarmFromUserType.js
  api-server/api/graphql/types/LogType.js
  api-server/api/models/User.js
  api-server/api/models/UserFollow.js
  api-server/api/services/LogService.js
  web/src/components/ToolTip/ToolTipWrapper.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/AlarmFollowButtn.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/styles.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmToolTipWrapper.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/index.js
  web/src/containers/Navigation/queries/index.js
Labels: confirmed-bug

#317 [Refact] UserPage, HashTagPage의 불필요한 useEffect 제거
  web/src/containers/HashTagPage/index.js
  web/src/containers/UserPage/index.js
Labels: front, refactor

#319 [Fix] postURL 유니크하게 생성되도록 수정
  api-server/api/services/PostService.js
  api-server/app.js
  api-server/package-lock.json
  api-server/package.json
Labels: confirmed-bug

#318 [팔로우버튼] followStatus에 따른 FollowButton 기능변화 리팩토링
  web/src/components/FollowButton/StyledFollowButton.js
  web/src/components/FollowButton/index.js
Labels: front, refactor

#320 [유저페이지] 유저페이지 변수명 수정 및 프로필사진 반영
  api-server/api/graphql/queries/UserPageQuery.js
  api-server/api/graphql/types/UserInfoType.js
  api-server/api/services/UserPageService.js
  web/src/containers/UserPage/UserPageInfo/index.js
  web/src/containers/UserPage/index.js
Labels: back, front, refactor

#321 Button컴포넌트 디자인 수정 및 UserPage 마이페이지 기능 추가
  web/src/components/Button/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/StyledFollowButton.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/UserNameLabel/UserNameLabelWrapper.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
  web/src/containers/UserPage/UserPageInfo/index.js
  web/src/containers/UserPage/index.js
Labels: feature, front, refactor

#323 [Feat] 회원가입/로그인 페이지 구현
  api-server/api/middlewares/Authenticator.js
  api-server/api/middlewares/auth.js
  api-server/api/routes/AccountRoute.js
  api-server/api/routes/account-route.js
  api-server/api/services/UserService.js
  api-server/app.js
  api-server/config/passport-config.js
  api-server/package-lock.json
  api-server/test/api/AccountRoute.test.js
  web/package-lock.json
  web/package.json
  web/src/containers/AccountPage/Background.js
  web/src/containers/AccountPage/HorizontalLine.js
  web/src/containers/AccountPage/SignButton.js
  web/src/containers/AccountPage/SignForm.js
  web/src/containers/AccountPage/SignHeader.js
  web/src/containers/AccountPage/SignIn/index.js
  web/src/containers/AccountPage/SignInput.js
  web/src/containers/AccountPage/SignLink.js
  web/src/containers/AccountPage/SignUp/index.js
  web/src/containers/AccountPage/SignWrapper.js
  web/src/containers/AccountPage/Title.js
  web/src/containers/AccountPage/ValidationMessage.js
  web/src/containers/AccountPage/constants/index.js
  web/src/containers/AccountPage/lib/encryptor.js
  web/src/containers/AccountPage/lib/handlers.js
  web/src/containers/AccountPage/lib/index.js
  web/src/containers/AccountPage/lib/validator.js
  web/src/containers/AccountPage/styles.js
  web/src/containers/App/AccountRoute.js
  web/src/containers/App/AuthRoute.js
  web/src/containers/App/index.js
  web/src/index.js
  web/src/utils/index.js
Labels: back, feature, front

#328 [Fix] cookie의 maxAge 값 수정
  api-server/api/middlewares/auth.js
Labels: confirmed-bug, fix

#326 [Fix] newpost page 버그 수정
  web/package-lock.json
  web/package.json
  web/src/containers/NewPostPage/Button.js
  web/src/containers/NewPostPage/Content.js
  web/src/containers/NewPostPage/FileInput.js
  web/src/containers/NewPostPage/FileNameInput.js
  web/src/containers/NewPostPage/FileSelectLabel.js
  web/src/containers/NewPostPage/Input.js
  web/src/containers/NewPostPage/NewPostWrapper.js
  web/src/containers/NewPostPage/hooks/useImage.js
  web/src/containers/NewPostPage/index.js
  web/src/containers/NewPostPage/lib/cropImage.js
  web/src/containers/NewPostPage/lib/makeNewImageFile.js
  web/src/containers/NewPostPage/styles.js
  web/src/utils/fileUtils.js
Labels: fix, refactor

#329 [Feat] 해시/사람 태그 구현
  web/src/containers/HomePage/Post/PostText/MainText/index.js
  web/src/containers/HomePage/Post/PostText/MainText/lib/index.js
Labels: feature, front

#332 [Fix] 새게시물 본문 입력 버그 수정
  web/src/containers/NewPostPage/index.js
Labels: confirmed-bug

#334 [Fix] session 버그 수정
  api-server/app.js
Labels: confirmed-bug, urgent

#335 [Fix] password Input 버그 수정
  web/src/containers/AccountPage/lib/encryptor.js
  web/src/containers/AccountPage/lib/handlers.js
  web/src/containers/AccountPage/lib/validator.js
  web/src/index.js
  web/src/utils/index.js
Labels: urgent

#360 [Fix] 서버에서 검색 안되는 버그 수정
  api-server/api/graphql/queries/SearchQuery.js
Labels: urgent

#362 [Fix] 로그아웃 시 초기화면이 보이지 않는 버그 수정
  web/src/containers/App/index.js
  web/src/containers/HomePage/Post/CommentInput/index.js
  web/src/containers/HomePage/index.js
  web/src/containers/NewPostPage/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/containers/PostDetailPage/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
Labels: confirmed-bug, fix

#366 [Fix] myInfo 쿠키 세팅 변경
  api-server/api/middlewares/auth.js
  api-server/api/routes/account-route.js
  api-server/api/services/UserService.js
Labels: fix

#367 [Fix] nginx 설정 변경
  web/config/nginx/conf.d/default.conf
Labels: urgent

#368 [Fix] 유저프로필 클릭 시 리다이렉트되는 버그 수정
  web/src/containers/App/AccountRoute.js
  web/src/containers/App/AuthRoute.js
  web/src/containers/App/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
Labels: fix

#370 [Fix] 새로고침 버그 수정
  api-server/api/routes/account-route.js
Labels: confirmed-bug

#379 [Feat] 댓글 남길시 로그에 남도록 추가
  api-server/api/graphql/mutations/CommentMutation.js
  api-server/api/graphql/types/UserType.js
  web/src/containers/HomePage/Post/CommentInput/index.js
  web/src/containers/HomePage/Post/PostMiddle/index.js
  web/src/containers/HomePage/Post/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
  web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/queries/createComment.js
  web/src/queries/followingPostList.js
  web/src/queries/readPost.js
Labels: 🔧feature, 🖥back

#380 [Fix] 알람 관련 버그 수정
  api-server/api/graphql/queries/LogQuery.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResultList.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/index.js
  web/src/queries/getLogs.js
Labels: 💻front, 🛠fix

#383 [Fix] post card에 배경색 추가
  web/src/components/PostCardList/PostCardLine/PostCard/MarginalPostCard.js
Labels: 💻front, 🛠fix

#382 [Fix] 게시물이 최신글부터 리스트되도록 수정
  api-server/api/services/HashTagPageService.js
  api-server/api/services/UserPageService.js
Labels: 🖥back, 🛠fix

#378 [Refact] destructuring으로 중복되는 코드 제거
  web/src/containers/HashTagPage/index.js
Labels: 💻front, 🚧refactor

#398 [Feat] 프로필 사진 편집 기능 구현
  api-server/api/graphql/index.js
  api-server/api/graphql/mutations/UserMutation.js
  api-server/api/graphql/mutations/index.js
  api-server/api/middlewares/auth.js
  api-server/api/services/UserService.js
  web/src/components/InputRow/StyledAside.js
  web/src/components/InputRow/index.js
  web/src/containers/EditProfilePage/UpdateProfile.js
  web/src/containers/EditProfilePage/Username.js
  web/src/containers/EditProfilePage/index.js
  web/src/containers/SettingPage/index.js
  web/src/queries/index.js
  web/src/queries/updateProfile.js
Labels: 🔧feature

#400 [Fix] 브라우저에 뜨는 react warning 제거
  web/src/containers/AccountPage/lib/encryptor.js
  web/src/containers/EditProfilePage/index.js
  web/src/containers/NewPostPage/Content.js
  web/src/containers/NewPostPage/CropContainer.js
  web/src/containers/NewPostPage/index.js
  web/src/containers/PostDetailPage/PostSideBox/PostContent/PostText/Content/index.js
  web/src/containers/SettingPage/List/index.js
  web/src/containers/SettingPage/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
Labels: 🛠fix

#404 [Fix] 알람 로그 에러 수정
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
Labels: 🏇urgent

#410 [Refact] 로그인 확인 방식, 유저 정보 접근 방식 변경
  web/src/containers/AccountPage/SignIn/index.js
  web/src/containers/AccountPage/SignUp/index.js
  web/src/containers/AccountPage/lib/handlers.js
  web/src/containers/App/AccountRoute.js
  web/src/containers/App/AuthRoute.js
  web/src/containers/App/UserContext.js
  web/src/containers/App/index.js
  web/src/containers/EditProfilePage/index.js
  web/src/containers/HomePage/Post/CommentInput/index.js
  web/src/containers/HomePage/index.js
  web/src/containers/NewPostPage/index.js
  web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
  web/src/containers/PostDetailPage/PostSideBox/context.js
  web/src/containers/PostDetailPage/PostSideBox/index.js
  web/src/containers/PostDetailPage/context.js
  web/src/containers/PostDetailPage/index.js
  web/src/containers/SettingPage/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
  web/src/index.js
Labels: 💻front, 🚧refactor

#415 [Feat] 유저 페이지에서 팔로우, 팔로워 클릭 시 해당하는 유저 리스트 출력하는 모달 구현
  api-server/api/graphql/index.js
  api-server/api/graphql/queries/FollowListQuery.js
  api-server/api/graphql/queries/FollowerListQuery.js
  api-server/api/graphql/queries/index.js
  api-server/api/graphql/types/UserType.js
  api-server/api/services/FollowListService.js
  web/src/components/UserListModal/ModalContent.js
  web/src/components/UserListModal/ModalHeader.js
  web/src/components/UserListModal/NoResult/NoResultWrapper.js
  web/src/components/UserListModal/NoResult/index.js
  web/src/components/UserListModal/UserListItem/index.js
  web/src/components/UserListModal/index.js
  web/src/components/UserListModal/styles.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/CountIndicatorWrapper.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/FollowIndicatorWrapper.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/index.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/styles.js
  web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
Labels: 💻front, 🔧feature, 🖥back

#417 [Feat] Authorization Code Grant 방식 구현
  oauth-server/.gitignore
  oauth-server/.sequelizerc
  oauth-server/app.js
  oauth-server/bin/www
  oauth-server/config/passport-config.js
  oauth-server/config/sequelize-config.js
  oauth-server/db/index.js
  oauth-server/error-types/access-denied-error.js
  oauth-server/error-types/index.js
  oauth-server/error-types/invalid-client-error.js
  oauth-server/error-types/invalid-grant-error.js
  oauth-server/error-types/invalid-request-error.js
  oauth-server/error-types/invalid-scope-error.js
  oauth-server/error-types/server-error.js
  oauth-server/error-types/temporarily-unavailable-error.js
  oauth-server/error-types/unauthorized-client-error.js
  oauth-server/error-types/unsupported-grant-type-error.js
  oauth-server/error-types/unsupported-response-type-error.js
  oauth-server/grant-types/authorization-code.js
  oauth-server/grant-types/implicit.js
  oauth-server/grant-types/index.js
  oauth-server/lib/index.js
  oauth-server/middlewares/auth.js
  oauth-server/middlewares/index.js
  oauth-server/middlewares/request-validator.js
  oauth-server/models/client.js
  oauth-server/models/token.js
  oauth-server/models/user.js
  oauth-server/package-lock.json
  oauth-server/package.json
  oauth-server/public/css/signin.css
  oauth-server/public/images/icon-1.png
  oauth-server/public/js/signin.js
  oauth-server/routes/api.js
  oauth-server/routes/client.js
  oauth-server/routes/oauth.js
  oauth-server/services/client-service.js
  oauth-server/services/token-service.js
  oauth-server/services/user-service.js
  oauth-server/test/error-types/error-types.test.js
  oauth-server/test/lib/lib.test.js
  oauth-server/test/services/registration.test.js
  oauth-server/test/validator/validator.test.js
  oauth-server/validator/index.js
  oauth-server/views/index.html
  oauth-server/views/signin.html
Labels: 🔑oauth, 🖥back

#418 [Refact] PostCardList 컴포넌트 리팩토링
  web/src/components/PostCardList/PostCardLine/index.js
  web/src/components/PostCardList/index.js
Labels: 💻front, 🚧refactor

#419 [Feat] Session 저장소로 Redis 설정
  api-server/app.js
  api-server/config/redis-config.js
  api-server/package-lock.json
  api-server/package.json
Labels: 🖥back

#420 [Fix] 버그데이 버그 해결
  api-server/api/graphql/types/UserType.js
  web/src/components/FollowButton/index.js
  web/src/components/PostTop/MoreModal/index.js
  web/src/components/PostTop/MoreModal/styles/CustomFollowButton.js
  web/src/components/PostTop/MoreModal/styles/FollowCancelContent.js
  web/src/components/PostTop/MoreModal/styles/index.js
  web/src/containers/HomePage/index.js
  web/src/containers/NewPostPage/index.js
  web/src/containers/SettingPage/index.js
Labels: 🐛confirmed-bug, 💻front

#426 [Fix] SignIn, SignUp 페이지 Error 핸들링 구현
  api-server/api/middlewares/auth.js
  api-server/api/services/UserService.js
  web/src/containers/AccountPage/SignIn/index.js
  web/src/containers/AccountPage/SignIn/reducer.js
  web/src/containers/AccountPage/SignUp/index.js
  web/src/containers/AccountPage/SignUp/reducer.js
  web/src/containers/AccountPage/constants/index.js
  web/src/containers/AccountPage/lib/handlers.js
  web/src/containers/AccountPage/lib/validator.js
Labels: 🛠fix

#437 [Fix] graphql UserType 수정
  api-server/api/graphql/types/UserType.js
Labels: 🏇urgent

#435 [Fix] 메인게시물의 본문 더보기 버튼 오류 수정
  web/src/containers/HomePage/Post/PostText/MainText/index.js
  web/src/containers/HomePage/Post/PostText/styles/TextMoreButton.js
Labels: 🐛confirmed-bug, 🖥back

#434 [Fix] hashtag가 최대 44글자까지 파싱되도록 수정
  web/src/containers/HomePage/Post/PostText/MainText/lib/index.js
Labels: 🛠fix

#439 [Fix] connection pool 설정 적용
  api-server/config/sequelize-config.js
Labels: 🛠fix

#440 [Fix] 알람 내에서 팔로우 기능 가능하도록 수정
  api-server/api/graphql/types/AlarmFromUserType.js
  api-server/api/graphql/types/LogType.js
  web/src/components/ToolTip/index.js
  web/src/components/ToolTip/styles/ToolTipArrow.js
  web/src/components/ToolTip/styles/ToolTipBackground.js
  web/src/components/ToolTip/styles/ToolTipBody.js
  web/src/containers/App/index.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
  web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/styles/AlarmActionWrapper.js
  web/src/containers/Navigation/Alarm/index.js
  web/src/containers/Navigation/Alarm/style/AlarmToolTipWrapper.js
  web/src/containers/Navigation/Alarm/style/index.js
  web/src/containers/Navigation/Search/styles/Input.js
  web/src/containers/Navigation/index.js
  web/src/queries/getLogs.js
Labels: 🛠fix

#441 [Feat] UserPage 태그됨 기능 구현
  api-server/api/graphql/index.js
  api-server/api/graphql/queries/TaggedPostsQuery.js
  api-server/api/graphql/queries/index.js
  web/src/components/PostCardList/index.js
  web/src/containers/UserPage/ListSelector/SelectionTab/index.js
  web/src/containers/UserPage/ListSelector/SelectionTab/styles/BorderTopLink.js
  web/src/containers/UserPage/ListSelector/SelectionTab/styles/TabText.js
  web/src/containers/UserPage/ListSelector/index.js
  web/src/containers/UserPage/index.js
Labels: 💻front, 🔧feature, 🖥back

#443 [Fix] client register 메소드 수정
  oauth-server/routes/client.js
  oauth-server/services/client-service.js
Labels: 🛠fix

#428 [Feat] 유저가 등록한 앱 목록 페이지 구현
  api-server/api/graphql/index.js
  api-server/api/graphql/queries/ClientQuery.js
  api-server/api/graphql/queries/index.js
  api-server/api/graphql/types/ClientType.js
  api-server/api/graphql/types/index.js
  api-server/api/models/Client.js
  web/src/containers/App/index.js
  web/src/containers/MyAppPage/MyAppList.js
  web/src/containers/MyAppPage/MyApplication.js
  web/src/containers/MyAppPage/index.js
  web/src/containers/MyAppPage/styles/ModalContent.js
  web/src/containers/MyAppPage/styles/ModalContentTitle.js
  web/src/containers/MyAppPage/styles/ModalRow.js
  web/src/containers/MyAppPage/styles/MyAppInfo.js
  web/src/containers/MyAppPage/styles/MyAppListWrapper.js
  web/src/containers/MyAppPage/styles/MyAppNoResult.js
  web/src/containers/MyAppPage/styles/index.js
  web/src/queries/getClient.js
  web/src/queries/index.js
Labels: 💻front, 🔧feature, 🖥back

#442 [Fix] 클라이언트 등록 버그 수정
  web/src/containers/RegisterAppPage/index.js
Labels: 💻front, 🛠fix

#444 [Fix] graphql type때문에 생긴 오류 수정
  api-server/api/graphql/mutations/UserMutation.js
Labels: 🏇urgent

#449 [Refact] UserListModal에서 본인 계정의 FollowButton 렌더링 방지
  web/src/components/UserListModal/UserListItem/index.js
Labels: 💻front, 🛠fix

#451 [Fix] FollowButton 주석, default props 삭제
  web/src/components/FollowButton/index.js
Labels: 💻front, 🛠fix

#462 [Refact] TaggedPosts 쿼리 myId변수 타입 수정
  api-server/api/graphql/queries/TaggedPostsQuery.js
  web/src/queries/taggedPosts.js
Labels: 🚧refactor

#463 [Fix] 프로필 편집 페이지 오류 수정
  api-server/api/services/user-service.js
  web/src/containers/EditProfilePage/index.js
Labels: 🛠fix

#465 [Feat] Implicit grant type 구현
  oauth-server/grant-types/authorization-code.js
  oauth-server/grant-types/implicit.js
  oauth-server/routes/oauth.js
Labels: 🔑oauth

#466 [Feat] refresh token에 대한 처리 구현
  oauth-server/grant-types/authorization-code.js
  oauth-server/middlewares/request-validator.js
  oauth-server/routes/oauth.js
  oauth-server/services/token-service.js
Labels: 🔑oauth

#468 [Refact] 팔로우, 팔로워 조회시 쿼리 최적화
  api-server/api/graphql/queries/FollowListQuery.js
  api-server/api/graphql/queries/FollowerListQuery.js
  api-server/api/services/followlist-service.js
Labels: 🖥back, 🚧refactor

#480 [Fix] 팔로우가 없는 경우 랜덤 추천 팔로우 구현
  api-server/api/graphql/index.js
  api-server/api/graphql/queries/RandomListQuery.js
  api-server/api/graphql/queries/index.js
  api-server/api/services/randomlist-service.js
  api-server/error/index.js
  web/src/containers/HomePage/NoFollowing/index.js
  web/src/containers/HomePage/NoFollowing/styles/NoFollowingWrapper.js
  web/src/containers/HomePage/NoFollowing/styles/StyledModalContent.js
  web/src/containers/HomePage/NoFollowing/styles/StyledModalWrapper.js
  web/src/containers/HomePage/NoFollowing/styles/index.js
  web/src/containers/HomePage/index.js
  web/src/queries/randomList.js
Labels: 💻front, 🔧feature, 🖥back

#481 [Fix] 검색 기능 버그 수정
  web/src/containers/Navigation/Search/SearchToolTip/index.js
  web/src/containers/Navigation/Search/index.js
Labels: 💻front, 🛠fix

#493 [Fix] 사용하지 않는 페이지라 사용되지 않는 코드 삭제
  web/src/containers/App/index.js
Labels: 💻front, 🛠fix

#495 [Refact] UserPage에서 쿠키로 myInfo 받도록 수정
  web/src/containers/App/index.js
  web/src/containers/UserPage/index.js
Labels: 💻front, 🚧refactor

#498 [Fix] 사용하지 않는 테스트코드와 폴더 삭제
  web/src/__test__/utils.test.js
Labels: 🚃qa
